In [1]:
import numpy as np

### Урок 7. Многомерный статистический анализ. Линейная регрессия

#### Задание №1
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
# Найдём коэффициент b 
b = (np.mean(zp*ks) - np.mean(zp) * np.mean(ks)) / (np.mean(zp**2) - (np.mean(zp))**2)
b

2.620538882402765

In [4]:
# Найдём коэффициент a 
a = np.mean(ks) - b * np.mean(zp)
a

444.1773573243596

In [5]:
y_hat = a + b * zp
y_hat

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

y_hat = 444.177 + 2.62*x


In [6]:
# Без интерсептера
zp1 = zp.reshape(10,1)
ks1 = ks.reshape(10,1)

In [7]:
b1 = np.dot(np.linalg.inv(np.dot(zp1.T, zp1)), zp1.T@ks1)
b1

array([[5.88982042]])

In [8]:
y2_hat = b1 * zp
y2_hat

array([[ 206.1437147 ,  265.04191891, 1119.06587983, 1177.96408403,
         235.59281681,  412.28742941,  318.05030269,  883.47306302,
         706.77845042,  647.88024621]])

y2_hat = 5.889 * x

#### Задание №2
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept). 

In [9]:
alpha = 10**-6

In [10]:
b1 = 3

In [11]:
for i in range(1000):
  b1 -= alpha * (2/len(zp)) * np.sum((b1*zp-ks)*zp)
  if i%100==0:
    print(b1)

3.0796238
5.71790221780173
5.879303053454158
5.889177003668632
5.88978105811757
5.889818012099447
5.889820272817466
5.889820411120448
5.889820419581351
5.8898204200989595


y3_hat = 5.889 * x

#### Задание №3
 Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [12]:
b0 = 400
b1 = 2
alpha = 10**-4.2
for i in range(1000000):
  b0 -= alpha * (2/len(zp)) * np.sum((b0 + b1*zp-ks))
  b1 -= alpha * (2/len(zp)) * np.sum((b0 + b1*zp-ks)*zp)
  if i%100000==0:
    print(b1, b0)

3.6439126157126074 400.0135151063188
2.633774304234221 442.37911677250474
2.621077732767596 444.1041460138506
2.6205608204806916 444.17437669088537
2.62053977556216 444.17723597458604
2.620538918765742 444.17735238387644
2.6205388838832078 444.1773571232182
2.620538882463047 444.1773573161694
2.6205388824093 444.17735732347177
2.6205388824093 444.17735732347177


y4_hat = 444.177 + 2.62*x